# Generated by Django 5.2.4 on 2025-07-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('MFJ', 'Married Filing Jointly'), ('MFS', 'Married Filing Separately'), ('HOH', 'Head of Household'), ('QSS', 'Qualifying Surviving Spouse')], max_length=6)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qualified_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxable_ordinary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('ordinary_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lower_ordinary_bound', models.DecimalField(decimal_places=2, max_digits=11)),
                ('upper_ordinary_bound', models.DecimalField(decimal_places=2, max_digits=11)),
                ('prior_ordinary_bracket_tax', models.DecimalField(decimal_places=2, max_digits=11)),
                ('ordinary_tax', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qualified_tax', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.user')),
            ],
        ),
        migrations.CreateModel(
            name='Calcultion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.user')),
            ],
        ),
    ]
