# Generated by Django 5.2.4 on 2025-07-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdata',
            name='lower_ordinary_bound',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='ordinary_rate',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='ordinary_tax',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='prior_ordinary_bracket_tax',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='qualified_tax',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='taxdata',
            name='upper_ordinary_bound',
        ),
    ]
