# Generated by Django 5.2.4 on 2025-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_remove_taxdata_lower_ordinary_bound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdata',
            name='taxable_ordinary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=11),
        ),
    ]
