# Generated by Django 5.2.4 on 2025-07-19 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_alter_taxdata_user_alter_calcultion_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018')], max_length=4)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('MFJ', 'Married Filing Jointly'), ('MFS', 'Married Filing Separately'), ('HOH', 'Head of Household'), ('QSS', 'Qualifying Surviving Spouse')], max_length=6)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qualified_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxable_ordinary', models.DecimalField(decimal_places=2, editable=False, max_digits=11)),
                ('user', models.ManyToManyField(to='tax.taxdataset')),
            ],
        ),
        migrations.DeleteModel(
            name='TaxData',
        ),
    ]
