# Generated by Django 5.2.4 on 2025-07-20 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_taxdataset_taxyeardata_delete_taxdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
