# Generated by Django 5.2.4 on 2025-07-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0009_remove_taxdataset_years_taxyeardata_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxyeardata',
            name='lower_ordinary_bound',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='ordinary_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='ordinary_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='prior_ordinary_bracket_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='qualified_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='upper_ordinary_bound',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CalculationIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.PositiveIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='tax.taxdataset')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustedYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018')], max_length=4)),
                ('filing_status', models.CharField(choices=[('single', 'Single'), ('MFJ', 'Married Filing Jointly'), ('MFS', 'Married Filing Separately'), ('HOH', 'Head of Household'), ('QSS', 'Qualifying Surviving Spouse')], max_length=6)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('qualified_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxable_ordinary', models.DecimalField(decimal_places=2, editable=False, max_digits=11)),
                ('ordinary_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lower_ordinary_bound', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upper_ordinary_bound', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prior_ordinary_bracket_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordinary_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qualified_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusted_years', to='tax.calculationiteration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleJForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_j_form', to='tax.calculationiteration')),
            ],
        ),
        migrations.DeleteModel(
            name='Calcultion',
        ),
    ]
