# Generated by Django 5.2.4 on 2025-07-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0010_taxyeardata_lower_ordinary_bound_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdjustedYearData',
            new_name='AdjustedTaxData',
        ),
    ]
