# Generated by Django 5.2.4 on 2025-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0011_rename_adjustedyeardata_adjustedtaxdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdataset',
            name='max_elected_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxdataset',
            name='name',
            field=models.CharField(default='Set for <django.db.models.fields.related.ForeignKey>', max_length=50),
        ),
        migrations.AddField(
            model_name='taxdataset',
            name='qualified_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
