# Generated by Django 5.2.4 on 2025-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0012_taxdataset_max_elected_farm_income_taxdataset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdataset',
            name='name',
            field=models.CharField(default='Created Set', max_length=50),
        ),
    ]
