# Generated by Django 5.2.4 on 2025-08-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0014_schedulejform_line_2a_schedulejform_line_2b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulejform',
            old_name='line-2a',
            new_name='line_2a',
        ),
        migrations.RenameField(
            model_name='schedulejform',
            old_name='line-2b',
            new_name='line_2b',
        ),
        migrations.RenameField(
            model_name='schedulejform',
            old_name='line-2c',
            new_name='line_2c',
        ),
    ]
