# Generated by Django 5.2.4 on 2025-08-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0015_rename_line_2a_schedulejform_line_2a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulejform',
            name='iteration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='tax.calculationiteration'),
        ),
    ]
