# Generated by Django 5.2.4 on 2025-08-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0016_alter_schedulejform_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationiteration',
            name='iteration_number',
        ),
        migrations.AddField(
            model_name='taxdataset',
            name='ordinary_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxdataset',
            name='max_elected_farm_income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxdataset',
            name='qualified_farm_income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
