# Generated by Django 5.2.4 on 2025-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0019_alter_taxdataset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdataset',
            name='name',
            field=models.CharField(default='Created Set', max_length=200),
        ),
    ]
