# Generated by Django 5.2.4 on 2025-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0020_alter_taxdataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulejform',
            name='tax_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
