# Generated by Django 5.2.4 on 2025-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0021_schedulejform_tax_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdataset',
            name='income_worksheet',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
