# Generated by Django 5.2.4 on 2025-11-08 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0022_taxdataset_income_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustedtaxdata',
            name='elected_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='adjustedtaxdata',
            name='is_electing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adjustedtaxdata',
            name='qualified_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='elected_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='is_electing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxyeardata',
            name='qualified_farm_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.CreateModel(
            name='ScheduleJOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(blank=True, default=dict, null=True)),
                ('best_result', models.JSONField(blank=True, default=dict, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.taxdataset')),
            ],
        ),
    ]
