# Generated by Django 5.2.4 on 2025-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0024_remove_calculationiteration_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxyeardata',
            name='taxable_ordinary',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=11, null=True),
        ),
    ]
