# Generated by Django 5.2.4 on 2025-12-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0025_alter_taxyeardata_taxable_ordinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxyeardata',
            name='taxable_ordinary',
        ),
    ]
