# Generated by Django 5.2.4 on 2026-01-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0026_remove_taxyeardata_taxable_ordinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxyeardata',
            name='lower_ordinary_bound',
        ),
        migrations.RemoveField(
            model_name='taxyeardata',
            name='ordinary_rate',
        ),
        migrations.RemoveField(
            model_name='taxyeardata',
            name='ordinary_tax',
        ),
        migrations.RemoveField(
            model_name='taxyeardata',
            name='prior_ordinary_bracket_tax',
        ),
        migrations.RemoveField(
            model_name='taxyeardata',
            name='qualified_tax',
        ),
        migrations.RemoveField(
            model_name='taxyeardata',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='taxyeardata',
            name='upper_ordinary_bound',
        ),
    ]
